# Generated by Django 4.2 on 2026-05-10 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(choices=[('reminder', 'Reminder Skrining'), ('pesan', 'Pesan dari Kader'), ('jadwal', 'Info Jadwal'), ('sistem', 'Sistem')], default='pesan', max_length=20)),
                ('dibaca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_masuk', to=settings.AUTH_USER_MODEL)),
                ('pengirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifikasi_keluar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
