# Generated by Django 4.2 on 2026-05-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaderProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posyandu', models.CharField(blank=True, max_length=255)),
                ('wilayah', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kader_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Kader Posyandu',
                'verbose_name_plural': 'Profil Kader Posyandu',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='kader.kaderprofil')),
            ],
            options={
                'verbose_name': 'Jadwal Kader',
                'verbose_name_plural': 'Jadwal Kader',
                'ordering': ['tanggal', 'waktu'],
            },
        ),
    ]
