# Generated by Django 4.2 on 2026-05-10 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_masuk', to=settings.AUTH_USER_MODEL)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_keluar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesan',
                'verbose_name_plural': 'Pesan',
                'ordering': ['created_at'],
            },
        ),
    ]
