# Generated by Django 4.2 on 2026-05-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbuProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('usia_kehamilan', models.IntegerField(blank=True, help_text='Dalam minggu', null=True)),
                ('paritas', models.IntegerField(blank=True, help_text='Jumlah anak', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kader.kaderprofil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ibu_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Ibu Hamil',
                'verbose_name_plural': 'Profil Ibu Hamil',
            },
        ),
        migrations.CreateModel(
            name='SkriningHasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('kategori_risiko', models.CharField(choices=[('rendah', 'Risiko Rendah'), ('sedang', 'Risiko Sedang'), ('tinggi', 'Risiko Tinggi')], max_length=10)),
                ('jawaban', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ibu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skrining_hasil', to='ibu.ibuprofil')),
            ],
            options={
                'verbose_name': 'Hasil Skrining',
                'verbose_name_plural': 'Hasil Skrining',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiagaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_item', models.IntegerField()),
                ('sudah_dicentang', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ibu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siaga_checklist', to='ibu.ibuprofil')),
            ],
            options={
                'verbose_name': 'Siaga Checklist',
                'verbose_name_plural': 'Siaga Checklist',
                'unique_together': {('ibu', 'nomor_item')},
            },
        ),
    ]
