# Generated by Django 4.2 on 2026-05-09 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikelEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('ringkasan', models.TextField(blank=True)),
                ('konten', models.TextField()),
                ('kategori', models.CharField(choices=[('kecemasan', 'Kecemasan'), ('depresi', 'Depresi'), ('nutrisi', 'Nutrisi'), ('persalinan', 'Persiapan Persalinan'), ('bayi', 'Perawatan Bayi'), ('umum', 'Umum')], default='umum', max_length=20)),
                ('diterbitkan', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_edukasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artikel Edukasi',
                'verbose_name_plural': 'Artikel Edukasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
