# Generated by Django 4.2 on 2026-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibu', '0003_artikel_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibuprofil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
    ]
